---
title: "Makeover Monday - Explore heatmap"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(maps)
library(paletteer)
```

```{r}
usa <- map_data("usa")
states <- map_data("state")
```

```{r}
incometbl <- read_csv("incometbl_vote.csv")
head(incometbl)
```

```{r}
# Spread income so we can plot heatmap by category
# and create a new column with key "region" to merge
# "states" table
incometbl2 <- incometbl %>% spread(incomecat, catpct) %>% 
              mutate(region = tolower(state)) %>% 
              select(-state)

head(incometbl2)
```

Inspirational [link](https://stackoverflow.com/questions/32148564/heatmap-plot-by-value-using-ggmap)

```{r}
head(states)
```

```{r}
# join two data sets for mapping
states2 <- states %>% left_join(incometbl2, by = "region")
head(states2)
```

```{r}
# Start mapping with one category `>150K`
states2 %>% ggplot() +
              geom_polygon(aes(x = long, y = lat, fill = `>$150K`, group = group))+
              coord_fixed(1.3)

glimpse(states2)
```

* Note how for the top income category, the states with higher portion are scattered to the northeast and California.

* We can reorganize the data table to create a grid by income levels

```{r}
# First way to create a merged table states3
states3 <- states2 %>% gather(incomecat, catpct, -region, -long, -lat, 
                   -group, -order, -subregion)


# Another way to create merged table states3
incometbl3 <- incometbl %>% mutate(region = tolower(state)) %>% select(-state)
head(incometbl3)
states3 <- states %>% inner_join(incometbl3, by = "region")


# convert income_cat to factor
incomecat_levels <- factor(c("<$25K", "$25K-$50K", "$51K-$75K",
                      "$76K-$100K", "$101K-$150K", ">$150K"))
states3[,"incomecat"] <- factor(states3[,"incomecat"], levels = incomecat_levels)
?as.factor


summary(states3$incomecat)
# There are some missing values for DC
#states3[(is.na(states3$incomecat)),]

```

```{r}

```

```{r}
class(states3$incomecat)
```


```{r}
glimpse(states3)

summary(states3$catpct)

# Try new plotting with facet
states3 %>% filter(!is.na(incomecat)) %>% 
        arrange(incomecat) %>% 
            ggplot() +
            geom_polygon(aes(x = long, y = lat, 
                             fill = catpct, 
                             group = group,
                             color = winner)) +
            facet_wrap(.~ incomecat) +
            coord_fixed(1.3) +
            scale_fill_brewer(palette = "Greens") +
            scale_color_manual(values = c("blue", "red"))

?scale_fill_paletteer_c

# Change the pallete to make the graphs pop: paletteer for details.
```

```{r}
# Create plot
plot_category <- function(cat){
result <- states3 %>% filter(incomecat == cat) %>% 
            mutate(percentage = cut_interval(catpct, n = 6)) %>% 
            ggplot() +
            geom_polygon(aes(x = long, y = lat,
                             fill = percentage, 
                             group = group,
                             color = winner))+
            scale_fill_manual(values = 
                                c('#8c510a','#d8b365','#f6e8c3','#c7eae5','#5ab4ac','#01665e')) +
            scale_color_manual(values = c("black", "red")) +
            coord_fixed(1.3) +
            ggtitle(paste("Distribution of income group", cat))
print(result)
}     

for (cat in as.character(incomecat_levels)) { plot_category(cat)}
```

Notes: some nice [tutorial(http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html) on maps
